### PR TITLE
Set Basel Bad Bf as not_suggestable

### PR DESCRIPTION
**Pull request by Diego-Thomaz**
It seems no results are being displayed for this station. This station seem to be the same one as Basel Badischer Bahnhof, which we have results.

### CODE REVIEW

**Review by trainline-kamchanliu — APPROVED** [review]
LGTM

**Review by lsolino — APPROVED** [review]

**Comment by matheussilvasantos** [comment]
I think this station could be deleted instead. I don't see a real difference between it and 7395.

**Comment by matheussilvasantos** [comment]
@misdoro, do you think this could be removed/merged into 7395?

**Comment by misdoro** [comment]
> @misdoro, do you think this could be removed/merged into 7395?

We should not be deleting stations, for various reasons. You may set "same_as" column with an ID if you want to link to a different station.

**Pull request merged**
