### PR TITLE
Add station for the City Airport Train from Vienna and their DB id

### PR DESCRIPTION
**Pull request by noplay**

### CODE REVIEW

**Comment by inouire** [comment]
Are we sure we want to put a carrier name in a station name ? Oo

**Comment by noplay** [comment]
It's what I get from Hafas

**Comment by noplay** [comment]
I don't know why they have  a specific DB id.

**Comment by inouire** [comment]
Given the fact that there is no other "Wien Mitte" nor "Flughafen Wien" stations, do we really have to add the suffixes? By the way I think Wien Flughafen would be more consistent with the rest of the file.

**Comment by noplay** [comment]
Flughafen Wien exists with id: "23019" and a DB id (i can rename it)
Wien Mitte exists with id: "23588" (and a DB id)

I can amend the PR in order to have:
Wien Flughafen (CAT)
Wien Mitte-Landstraße

And also rename Flughafen Wien to Wien Flughafen

**Comment by inouire** [comment]
Oops I missed them. OK for your proposals

**Comment by noplay** [comment]
Commit amend

**Comment by inouire** [comment]
You have to fix the slug too

**Comment by inouire** [comment]
Why not "Wien Flughafen (CAT)"?

**Comment by noplay** [comment]
Commit amend for Wien Flughafen (CAT)

If we change the slug we will broke existing links. Like this one:
https://www.trainline.fr/horaires-train/flughafen-wien-a-wien-hbf

Are we ok with that?

**Comment by noplay** [comment]
OK I fixed the slug

**Pull request merged**
