### PR TITLE
Add DB IDs for new bus stations

### PR DESCRIPTION
**Pull request by lucavezz**
Udine Stazione (Viale Europa Unita; Villach Hbf (Busbahnhof)

### CODE REVIEW

**Comment by noplay** [comment]
HI Lucas it seem you put the ids in the wrong field (SNCF instead of DB)

**Comment by lucavezz** [comment]
I think I missed entirely one field :-P
Now it should be ok, but the test fails for reasons I do not understand :thinking:

**Comment by noplay** [comment]
I think stations studio is broken

**Comment by lucavezz** [comment]
No ok, I found the issue and it is now OK. I misplaced the parent_id field :-P

**Pull request merged**
