### PR TITLE
Update French station coordinates

### PR DESCRIPTION
**Pull request by mckbrmn**
All updated from the data in https://ressources.data.sncf.com/explore/dataset/referentiel-gares-voyageurs/

### CODE REVIEW

**Comment by espadrine** [comment]
Could you provide the script you have used to automate that change please?

Also, it would be interesting for the purpose of the review to rank the changes starting with the one with the largest distance to the original location.

**Comment by mckbrmn** [comment]
Here's a cleaned up version of the script used:
```ruby
#!/usr/bin/env ruby

require 'csv'
require 'json'

CSV_PARAMS = { headers: true, col_sep: ';', encoding: 'UTF-8' }

# Read files
stations_csv = CSV.read('stations.csv', CSV_PARAMS)
sncf_stations = JSON.parse(File.read('referentiel-gares-voyageurs.json'))

sncf_stations.each do |sncf_station|
  # Attempt to find a matching station by UIC (present for most SNCF stations)
  station = stations_csv.find do |s|
    !sncf_station['fields']['uic'].nil? && s['uic'] == sncf_station['fields']['uic'][2..8]
  end

  # Attempt by TVS id (also present for almost all SNCF stations)
  # Only there for Cenon (4845)
  if station.nil?
    station = stations_csv.find do |s|
      !s['sncf_tvs_id'].nil? && s['sncf_tvs_id'] == sncf_station['fields']['tvs']
    end
  end

  # No point in updating an unmatched station
  if station.nil?
    next
  end

  # Update coordinates
  if !sncf_station['fields']['latitude_wgs84'].nil? && !sncf_station['fields']['longitude_wgs84'].nil?
    station['longitude'] = sncf_station['fields']['longitude_wgs84']
    station['latitude'] = sncf_station['fields']['latitude_wgs84']
  end
end

# Output updated stations.csv
output_csv = CSV.open('stations.csv', 'w', CSV_PARAMS)
output_csv << stations_csv.headers
stations_csv.each { |row| output_csv << row }
```

**Comment by mckbrmn** [comment]
Here are the 100 stations with the largest Haversine distance between the coordinates in `stations.csv` and the SNCF file used:

1. 11.09 km: Corrèze \[2734\] (`45.4166670000, 1.9500000000` vs `45.3294801, 1.8810793`)
2. 7.62 km: Bonnières \[1950\] (`49.0166670000, 1.4833330000` vs `49.038788, 1.582205`)
3. 6.14 km: Breteuil Embranchement \[1431\] (`49.6333330000, 2.3000000000` vs `49.626389, 2.3845164`)
4. 5.58 km: St-Denis \[9981\] (`48.9000000000, 2.4000000000` vs `48.9354933, 2.3459524`)
5. 4.09 km: Mauzens-Miremont \[2796\] (`45.0000000000, 0.9166670000` vs `44.9768912, 0.9571897`)
6. 3.82 km: Berre \[4129\] (`43.4666670000, 5.1833330000` vs `43.5008861, 5.1789508`)
7. 3.76 km: Gevrey-Chambertin \[3543\] (`47.2333330000, 4.9500000000` vs `47.2274694, 4.999058`)
8. 3.73 km: Pouzauges \[2273\] (`46.7833330000, -0.8333330000` vs `46.7523536, -0.8146784`)
9. 3.69 km: Pléchâtel \[2024\] (`47.9000000000, -1.7500000000` vs `47.8719509, -1.7763615`)
10. 3.61 km: Deûlémont \[1320\] (`50.7333330000, 2.9500000000` vs `50.7159172, 2.9933077`)
11. 3.53 km: Plénée-Jugon \[2049\] (`48.3666670000, -2.4000000000` vs `48.376656, -2.3546108`)
12. 3.47 km: Cordemais \[2210\] (`47.2833330000, -1.8833330000` vs `47.3021502, -1.8466771`)
13. 3.43 km: Écouflant \[2212\] (`47.5333330000, -0.5333330000` vs `47.5039036, -0.5194782`)
14. 3.32 km: Chabenet \[2815\] (`46.6166670000, 1.4666670000` vs `46.6265259, 1.5076773`)
15. 3.27 km: Luc-la-Primaube \[3016\] (`44.3166670000, 2.5333330000` vs `44.2913982, 2.5544751`)
16. 3.25 km: St-Georges-d’Aurac \[5178\] (`45.1500000000, 3.5333330000` vs `45.1605341, 3.4947035`)
17. 3.22 km: Lalinde \[2648\] (`44.83673401197435, 0.7021111249923706` vs `44.8396152, 0.7427811`)
18. 3.18 km: L’Aiguille \[2717\] (`45.7500000000, 1.2000000000` vs `45.7783702, 1.2049024`)
19. 3.09 km: Le Vauriat \[3097\] (`45.860294, 2.920469` vs `45.8337747, 2.9084747`)
20. 3.09 km: Guillerval \[2363\] (`48.3666670000, 2.1000000000` vs `48.3744455, 2.0598748`)
21. 3.08 km: Luant \[2813\] (`46.7333330000, 1.5500000000` vs `46.7357683, 1.5901964`)
22. 3.07 km: Landivisiau \[2102\] (`48.5156378130935, -4.052925109863281` vs `48.496002, -4.082181`)
23. 3.06 km: Plounérin \[2058\] (`48.5666670000, -3.5333330000` vs `48.5816298, -3.5682311`)
24. 3.04 km: St-Aulaire \[2756\] (`45.2333330000, 1.3666670000` vs `45.2488414, 1.3986965`)
25. 2.99 km: Bains-les-Bains \[530\] (`48.0000000000, 6.2666670000` vs `47.9811282, 6.2952683`)
26. 2.98 km: Saulon \[3551\] (`47.2166670000, 5.0666670000` vs `47.224035, 5.1045991`)
27. 2.94 km: Yutz \[820\] (`49.354051, 6.170393` vs `49.361354, 6.2093949`)
28. 2.93 km: Plougonver \[2074\] (`48.4833330000, -3.3833330000` vs `48.4584133, -3.3704584`)
29. 2.89 km: Parempuyre \[2562\] (`44.9500000000, -0.5833330000` vs `44.9447032, -0.6193396`)
30. 2.87 km: Saône \[3630\] (`47.2333330000, 6.1166670000` vs `47.2097669, 6.1013089`)
31. 2.82 km: Paulhaguet \[3841\] (`45.2000000000, 3.5333330000` vs `45.2101978, 3.5004445`)
32. 2.80 km: Saincaize \[5263\] (`46.9076500000, 3.0840680000` vs `46.9314165, 3.0718704`)
33. 2.80 km: St-Cloud \[9568\] (`48.8333330000, 2.1833330000` vs `48.84541, 2.21687`)
34. 2.73 km: Achiet \[95\] (`50.1166670000, 2.7500000000` vs `50.1317525, 2.780168`)
35. 2.72 km: Kalhausen \[4586\] (`49.0166670000, 7.1500000000` vs `49.0350585, 7.125352`)
36. 2.71 km: Thionville \[5839\] (`49.332876273346976, 6.150755882263184` vs `49.353931, 6.169543`)
37. 2.70 km: Meursault \[3547\] (`46.9833330000, 4.7666670000` vs `46.9690497, 4.7954444`)
38. 2.66 km: Ste-Geneviève-des-Bois \[10106\] (`48.6333330000, 2.3333330000` vs `48.653245, 2.313161`)
39. 2.65 km: Fos-sur-Mer \[4134\] (`43.4377380000, 4.9445670000` vs `43.428029, 4.974579`)
40. 2.60 km: Aulnay-sous-Bois \[9884\] (`48.9500000000, 2.5166670000` vs `48.93179, 2.49431`)
41. 2.59 km: La Mothe-St-Héray \[2244\] (`46.36067143443812, -0.1126420497894287` vs `46.3807592, -0.1298415`)
42. 2.56 km: Fromental \[2706\] (`46.1666670000, 1.4000000000` vs `46.1715646, 1.4324317`)
43. 2.56 km: Coulibœuf \[1970\] (`48.9333330000, -0.0666670000` vs `48.9237487, -0.0984574`)
44. 2.55 km: Monistrol-d’Allier \[3843\] (`44.9500000000, 3.6333330000` vs `44.9696648, 3.6500424`)
45. 2.52 km: Ennevelin \[1328\] (`50.5333330000, 3.1333330000` vs `50.5492981, 3.1586612`)
46. 2.50 km: St-Thégonnec \[2104\] (`48.5166670000, -3.9500000000` vs `48.4942082, -3.9483116`)
47. 2.48 km: Mont-de-Terre \[1315\] (`50.632766, 3.070706` vs `50.6176672, 3.0966031`)
48. 2.47 km: Lille Porte de Douai \[1326\] (`50.6333330000, 3.0666670000` vs `50.6119054, 3.075837`)
49. 2.46 km: Coudekerque-Branche \[1150\] (`51.0333330000, 2.4000000000` vs `51.0177069, 2.3751425`)
50. 2.45 km: Chabons \[4062\] (`45.4166670000, 5.4333330000` vs `45.4383566, 5.4281009`)
51. 2.44 km: Penne \[2675\] (`44.3833330000, 0.8333330000` vs `44.3799858, 0.8029779`)
52. 2.44 km: Chasse-sur-Rhône \[1475\] (`45.5666670000, 4.8166670000` vs `45.58237, 4.794843`)
53. 2.42 km: Nantiat \[2709\] (`46.0166670000, 1.1833330000` vs `46.0056192, 1.1563734`)
54. 2.38 km: St-Denis-de-Pile \[2652\] (`45.0000000000, -0.2000000000` vs `44.9786053, -0.1980825`)
55. 2.38 km: St-Martin-du-Mont \[3949\] (`46.1000000000, 5.3333330000` vs `46.095871, 5.303003`)
56. 2.37 km: St-Avold \[881\] (`49.10538487281865, 6.70741081237793` vs `49.085873, 6.7206141`)
57. 2.37 km: Grande-Synthe \[1270\] (`51.0125000000, 2.2833330000` vs `51.0026884, 2.3133547`)
58. 2.35 km: Éguzon \[2817\] (`46.44232249467152, 1.5826696157455444` vs `46.4397694, 1.5521707`)
59. 2.35 km: Malain \[3520\] (`47.3166670000, 4.7833330000` vs `47.3270025, 4.8105362`)
60. 2.35 km: Châtel-Censoir \[3492\] (`47.5166670000, 3.6333330000` vs `47.5377695, 3.6350455`)
61. 2.34 km: Lapeyrouse \[3080\] (`46.2166670000, 2.8666670000` vs `46.2267825, 2.893393`)
62. 2.33 km: Gauriaguet \[2307\] (`45.0333330000, -0.4000000000` vs `45.0542936, -0.3992689`)
63. 2.33 km: Grésy-sur-Aix \[4018\] (`45.7166670000, 5.9500000000` vs `45.7245161, 5.9221751`)
64. 2.32 km: Bournezeau \[2262\] (`46.6333330000, -1.1666670000` vs `46.6518258, -1.1806169`)
65. 2.32 km: Baisieux \[1309\] (`50.6000000000, 3.2500000000` vs `50.61845, 3.2347796`)
66. 2.31 km: Sartrouville \[9513\] (`48.9500000000, 2.1833330000` vs `48.9379523, 2.1575173`)
67. 2.30 km: Laillé \[2021\] (`47.97804033660744, -1.7201060056686401` vs `47.9717527, -1.7495654`)
68. 2.30 km: Neuilly-St-Front \[314\] (`49.1666670000, 3.2666670000` vs `49.1871466, 3.2710249`)
69. 2.29 km: Einvaux \[421\] (`48.4833330000, 6.4000000000` vs `48.5034859, 6.3932959`)
70. 2.28 km: Pont-Melvez \[2073\] (`48.4500000000, -3.3166670000` vs `48.4702228, -3.3114444`)
71. 2.28 km: Holtzheim \[1035\] (`48.5500000000, 7.6333330000` vs `48.555688, 7.6630912`)
72. 2.27 km: Dingé \[2154\] (`48.3500000000, -1.7166670000` vs `48.3507382, -1.6859729`)
73. 2.27 km: Roquesérière \[2996\] (`43.7333330000, 1.6333330000` vs `43.7512472, 1.6198753`)
74. 2.26 km: Bussière-Galant \[2726\] (`45.62664763326196, 1.036410927772522` vs `45.6076224, 1.0261372`)
75. 2.23 km: Montaigut \[2833\] (`46.1166670000, 1.7333330000` vs `46.1367425, 1.7339815`)
76. 2.23 km: Marles-en-Brie \[9794\] (`48.7166670000, 2.8833330000` vs `48.733976, 2.868099`)
77. 2.22 km: Lamothe-Landerron \[2623\] (`44.5500000000, 0.0666670000` vs `44.5628433, 0.0451406`)
78. 2.22 km: Limeray \[2449\] (`47.4666670000, 1.0333330000` vs `47.4502088, 1.0499661`)
79. 2.20 km: Duttlenheim \[1038\] (`48.5255300000, 7.5657180000` vs `48.5453531, 7.5661529`)
80. 2.15 km: Rochy-Condé \[1459\] (`49.4166670000, 2.1833330000` vs `49.3986042, 2.1727344`)
81. 2.12 km: Pontgibaud \[3093\] (`45.8333330000, 2.8666670000` vs `45.8210001, 2.8458031`)
82. 2.10 km: Olonne-sur-Mer \[2266\] (`46.5333330000, -1.7833330000` vs `46.5486605, -1.76738`)
83. 2.08 km: Dréfféac \[2150\] (`47.4666670000, -2.0666670000` vs `47.4817568, -2.0503661`)
84. 2.07 km: Boucau \[3236\] (`43.5277040000, -1.4655590000` vs `43.5234217, -1.4905872`)
85. 2.07 km: Luttenbach-près-Munster \[754\] (`48.0166670000, 7.1166670000` vs `48.0352559, 7.1186307`)
86. 2.05 km: Dachstein \[1039\] (`48.5612720000, 7.5323300000` vs `48.5428546, 7.5330038`)
87. 2.04 km: Caffiers \[1553\] (`50.8333330000, 1.8000000000` vs `50.8500679, 1.8120345`)
88. 2.04 km: Monthermé \[626\] (`49.8833330000, 4.7333330000` vs `49.865621, 4.74053`)
89. 2.03 km: Crépieux-la-Pape \[3714\] (`45.8000000000, 4.8666670000` vs `45.8038348, 4.8922918`)
90. 2.01 km: Le Blanc-Mesnil \[9900\] (`48.9333330000, 2.4500000000` vs `48.93248, 2.47747`)
91. 2.01 km: St-Sébastien-sur-Loire Frêne Rond \[5100\] (`47.2076820000, -1.5033250000` vs `47.1903914, -1.4957437`)
92. 2.00 km: Ceyzériat \[3955\] (`46.1666670000, 5.3166670000` vs `46.1834877, 5.3258417`)
93. 1.98 km: Graffenstaden \[940\] (`48.5333330000, 7.7166670000` vs `48.5324375, 7.6897861`)
94. 1.98 km: Miniac \[2160\] (`48.5166670000, -1.9000000000` vs `48.5315134, -1.914787`)
95. 1.97 km: Liévin \[1613\] (`50.4166670000, 2.7666670000` vs `50.434139, 2.7716316`)
96. 1.97 km: Pont-de-l’Arche \[1946\] (`49.3000000000, 1.1666670000` vs `49.3170928, 1.1596559`)
97. 1.96 km: Masseret \[2767\] (`45.5333330000, 1.5166670000` vs `45.536175, 1.5415396`)
98. 1.96 km: Perrignier \[4007\] (`46.3000000000, 6.4500000000` vs `46.303259, 6.4249208`)
99. 1.96 km: Nevers Le Banlay \[4855\] (`46.9895620000, 3.1589980000` vs `47.0068974, 3.1636746`)
100. 1.96 km: Bouray \[10101\] (`48.5166670000, 2.3000000000` vs `48.533149, 2.290596`)

**Comment by mckbrmn** [comment]
There are 453 stations in `stations.csv` with a Haversine distance of a kilometer or more. I've manually compared about a hundred of the stations before coming to the conclusion that whoever set the coordinates in `stations.csv` was slightly intoxicated when doing so.

The coordinates in the SNCF file are quite accurate. I decided to update all our coordinates from there as it cannot be guaranteed that any of our coordinates are of sufficient quality.

**Pull request merged**
