### PR TITLE
Remove duplicate Benerail id

### PR DESCRIPTION
**Pull request by mgalibert**

### CODE REVIEW

**Comment by mckbrmn** [comment]
Which station is it a duplicate of and how did you know which one was right?

**Comment by mgalibert** [comment]
I realised this morning that I didn't check if the same DSB code had been matched multiple times.
And in fact, I matched one DSB code on two different stations:
- The first station (`Rødby`) was matched based on a perfect name match with `Roedby`.
- The second station (`Rødby Færge`) was matched based on its former Benerail ID (`DKVJS`).

I decided to keep `Rødby Færge` vs `Rødby` for a few reasons:

- The station was already suggestable.
- The station had the right Benerail ID (see [commit](https://github.com/trainline-eu/stations/commit/753869b688832878edecb545f42c2f3508ce31d0#diff-343cb43b41eb112ac36b605f1cff1f92L16792)
- That's the station Google Maps display as well.

**Comment by mgalibert** [comment]
It sounds like you are not convinced.

**Comment by mckbrmn** [comment]
Sorry I wanted to check something before merging.

**Pull request merged**
