### PR TITLE
Add Westbahn stations

### PR DESCRIPTION
**Pull request by jclg**
This adds Westbahn station ids and enables them.
Ids are sourced from the Westbahn API.

### CODE REVIEW

**Comment by noplay** [comment]
Salzburg was not already in the file?

**Comment by jclg** [comment]
You're right, it was for "Salzburg Hbf" (internal id: 17458).
I can undo it for "Salzburg" (internal id: 6994).

**Comment by jclg** [comment]
I checked for duplicated Westbahn ids. Same case for Amstetten station.
It should be ok now.

**Comment by ConscritNeuneu** [comment]
Closing this as it has bitrotted.

**Pull request closed without merging**
