### PR TITLE
Disable 165 obsolete SNCF stations

### PR DESCRIPTION
**Pull request by anaalta**
PAO decommissioned some city codes in May. Since then, when we send the old SNCF codes we get an `unknown locality` error. Since we did not get a changelog, we needed to analyse the changes and their impact ourselves. 
We identified the following situations:
1. new SNCF stations  -> list of UIC (51) that are not enabled for SNCF in our master file and that exist in the new SNCF file. May have some station that we do not have in our master file.
2. same UIC but CODE CHANGED. -> list of UIC (20) that have their code changed between the old and new SNCF files. ->  should be updated in our master file.
3. Obsolete SNCF  stations-> list of UIC (166) that do not exist anymore in the new SNCF file.

File with changes: [Bordeaux .xlsx](https://github.com/user-attachments/files/15984710/Bordeaux.xlsx)

### CODE REVIEW

**Comment by ConscritNeuneu** [comment]
You'll have to be careful with this one, as it was just fixed earlier to have as a parent `Genève` instead of `Genève, Cornavin`.
Genève Champel

**Comment by ConscritNeuneu** [comment]
Also I believe that we should rather delete obviously obsolete stations rather than make them just non suggestable.

**Comment by anaalta** [comment]
Ah! It was never my intention, I need to rebase, thanks for the heads up!
> You'll have to be careful with this one, as it was just fixed earlier to have as a parent `Genève` instead of `Genève, Cornavin`. Genève Champel

**Comment by ConscritNeuneu** [comment]
You still have test failures

**Comment by matheussilvasantos** [comment]
#### :heavy_minus_sign: Stations removed
— **17 – Vievola**
— **167 – Aspach-le-Haut**
— **168 – Aspach-le-Bas**
— **324 – St-Pierremont**
— **337 – Rosoy-sur-Amance**
— **338 – Bize**
— **339 – Anrosey**
— **363 – Villette**
— **364 – Colmey – Flabeuville**
— **367 – Ingolsheim**
— **424 – Xermamenil – Lamath**
— **426 – Gerbeviller**
— **427 – Moyen**
— **429 – Magnières**
— **432 – Coussey**
— **433 – Domremy-la-Pucelle**
— **449 – Adamswiller**
— **472 – Hortes**
— **475 – Laferté-sur-Amance**
— **499 – Maatz**
— **505 – Velles**
— **515 – Corgirnon**
— **516 – Rougeux**
— **520 – Roville-aux-Chênes**
— **564 – Jeanmenil**
— **567 – Dompaire**
— **568 – Brouvelieures**
— **572 – Bocquegney**
— **574 – Racecourt**
— **575 – Vélotte-et-Tatignecourt**
— **584 – Ste-Marguerite – Remomeix**
— **585 – Blanchifontaine**
— **586 – Frémifontaine**
— **589 – Vallois**
— **591 – Greux**
— **592 – Goussaincourt**
— **593 – Burey-la-Côte**
— **595 – Taillancourt**
— **669 – Uxegney**
— **671 – Darnieulles**
— **672 – Mattaincourt**
— **677 – Suippes**
— **701 – Vaucouleurs**
— **702 – Neuville-les-Vaucouleurs**
— **703 – Burey-en-Vaux**
— **704 – Maxey-sur-Vaise**
— **705 – Hasenrain**
— **709 – Blesme-Haussignemont**
— **716 – St-André (Haut Rhin)**
— **744 – Burnhaupt**
— **745 – Guewenheim**
— **746 – Sentheim**
— **748 – Masevaux**
— **749 – Sickert**
— **750 – Niederbruck**
— **751 – Kirchberg**
— **752 – Oberbruck**
— **772 – Malmerspach**
— **780 – Chèvremont**
— **816 – Knutange – Nilvange**
— **851 – Vatimont**
— **910 – Enchenberg**
— **918 – Charency-Vezin**
— **920 – Fontoy**
— **964 – Hattmatt**
— **965 – Dossenheim-sur-Zinsel**
— **966 – Neuwiller-les-Saverne**
— **970 – Kaltenhouse**
— **973 – Neubourg**
— **974 – Pfaffenhoffen**
— **975 – Bouxwiller**
— **980 – Philippsbourg**
— **982 – Eguelshardt**
— **999 – Menchhoffen**
— **1002 – Alteckendorf**
— **1004 – Griesbach le Bastberg**
— **1035 – Holtzheim**
— **1056 – Chatenois**
— **1057 – Val-de-Villé**
— **1059 – Lièpvre**
— **1060 – Ste-Croix-aux-Mines**
— **1069 – Arzviller**
— **1071 – Hommarting**
— **1088 – Fénétrange**
— **1089 – Niederstinzel**
— **1090 – Wolfskirchen**
— **1091 – Bischtroff-sur-Sarre**
— **1092 – Sarrewerden**
— **1101 – Frohmuhl**
— **1188 – Paris Gare du Nord 2**
— **1398 – Le Fréty St-Gorgon**
— **1399 – La Ferée**
— **1400 – Mainbressy**
— **1513 – Ire-le-Sec**
— **1534 – Marville**
— **1765 – Mauléon Brossardière**
— **1881 – Mondoubleau**
— **2080 – Kerbiquet**
— **2081 – Port-de-Carhaix**
— **2082 – Motreff**
— **2096 – Le Juch**
— **2112 – Henvic**
— **2113 – Plouenan – Kerlaudy**
— **2116 – Kernevel**
— **2117 – Scaër**
— **2125 – Guiscriff**
— **2129 – Tal-Ar-Groas**
— **2144 – St-Gérand**
— **2292 – Chiche**
— **2298 – Taillebourg**
— **2300 – Clion-sur-Seugne**
— **2302 – Fontaines-d’Ozillac**
— **2543 – Vouille**
— **3251 – Jatxou**
— **3255 – Louhossoa**
— **3266 – Dolleren**
— **3267 – Monswiller**
— **3268 – Wegscheid**
— **3269 – Zornhoff**
— **3278 – St-Gonnery**
— **3938 – Gérardmer les Bas-Rupts**
— **3941 – Gérardmer la Mauselaine**
— **3972 – Gerbeviller Foch**
— **4375 – Manduel – Redessan**
— **4549 – Cocheren Village**
— **4621 – Le Châtelard**
— **4703 – Lichtenberg**
— **4768 – Chaumont Quartier Foch**
— **4821 – Minversheim**
— **4943 – Pontivy Douric**
— **4959 – Phalsbourg**
— **4990 – Pontivy Napoléon**
— **5105 – Reipertswiller**
— **5259 – Buswiller**
— **5307 – Toulouse St-Michel**
— **5308 – Toulouse Langlade**
— **5310 – Toulouse Croix de Pierre**
— **5312 – Toulouse Jeanne d’Arc**
— **5313 – Toulouse Bellevue**
— **5554 – Toulouse la Pointe**
— **5696 – Longuyon Collège**
— **5698 – Montmédy Centre**
— **5708 – Sarrebourg Zone Industrielle**
— **5880 – Hommarting Tilleuls**
— **5881 – Arzviller Fontaines**
— **5882 – St-Louis (Moselle) Plan Incliné**
— **5883 – Guntzviller**
— **8979 – Remiremont Magdelaine**
— **8997 – Carhaix République**
— **10088 – St-Hilaire-de-Chaléons Centre**
— **10370 – Fontenay-le-Comte Gare Routière**
— **10450 – Toulouse Roseraie**
— **10509 – Myennes**
— **10528 – Uzel Aire de covoiturage (Berlouze)**
— **10800 – Loudéac Aire de covoiturage**
— **16798 – St-Louis (Moselle)**
— **16799 – Henridorff**
— **17026 – Mainbresson Centre**
— **17259 – Le Fief d’Artois**
— **17407 – Lamerey**
— **23043 – Toulouse Gironis**
— **23618 – Toulouse Chaussee**
#### Stations changed
- **747 – Lauw**
    - `sncf_is_enabled` is now disabled :x:

**Comment by matheussilvasantos** [comment]
#### :heavy_minus_sign: Stations removed
— **17 – Vievola**
— **167 – Aspach-le-Haut**
— **168 – Aspach-le-Bas**
— **324 – St-Pierremont**
— **337 – Rosoy-sur-Amance**
— **338 – Bize**
— **339 – Anrosey**
— **363 – Villette**
— **364 – Colmey – Flabeuville**
— **367 – Ingolsheim**
— **424 – Xermamenil – Lamath**
— **426 – Gerbeviller**
— **427 – Moyen**
— **429 – Magnières**
— **432 – Coussey**
— **433 – Domremy-la-Pucelle**
— **449 – Adamswiller**
— **472 – Hortes**
— **475 – Laferté-sur-Amance**
— **499 – Maatz**
— **505 – Velles**
— **515 – Corgirnon**
— **516 – Rougeux**
— **520 – Roville-aux-Chênes**
— **564 – Jeanmenil**
— **567 – Dompaire**
— **568 – Brouvelieures**
— **572 – Bocquegney**
— **574 – Racecourt**
— **575 – Vélotte-et-Tatignecourt**
— **584 – Ste-Marguerite – Remomeix**
— **585 – Blanchifontaine**
— **586 – Frémifontaine**
— **589 – Vallois**
— **591 – Greux**
— **592 – Goussaincourt**
— **593 – Burey-la-Côte**
— **595 – Taillancourt**
— **669 – Uxegney**
— **671 – Darnieulles**
— **672 – Mattaincourt**
— **677 – Suippes**
— **701 – Vaucouleurs**
— **702 – Neuville-les-Vaucouleurs**
— **703 – Burey-en-Vaux**
— **704 – Maxey-sur-Vaise**
— **705 – Hasenrain**
— **709 – Blesme-Haussignemont**
— **716 – St-André (Haut Rhin)**
— **744 – Burnhaupt**
— **745 – Guewenheim**
— **746 – Sentheim**
— **748 – Masevaux**
— **749 – Sickert**
— **750 – Niederbruck**
— **751 – Kirchberg**
— **752 – Oberbruck**
— **772 – Malmerspach**
— **780 – Chèvremont**
— **816 – Knutange – Nilvange**
— **851 – Vatimont**
— **910 – Enchenberg**
— **918 – Charency-Vezin**
— **920 – Fontoy**
— **964 – Hattmatt**
— **965 – Dossenheim-sur-Zinsel**
— **966 – Neuwiller-les-Saverne**
— **970 – Kaltenhouse**
— **973 – Neubourg**
— **974 – Pfaffenhoffen**
— **975 – Bouxwiller**
— **980 – Philippsbourg**
— **982 – Eguelshardt**
— **999 – Menchhoffen**
— **1002 – Alteckendorf**
— **1004 – Griesbach le Bastberg**
— **1035 – Holtzheim**
— **1056 – Chatenois**
— **1057 – Val-de-Villé**
— **1059 – Lièpvre**
— **1060 – Ste-Croix-aux-Mines**
— **1069 – Arzviller**
— **1071 – Hommarting**
— **1088 – Fénétrange**
— **1089 – Niederstinzel**
— **1090 – Wolfskirchen**
— **1091 – Bischtroff-sur-Sarre**
— **1092 – Sarrewerden**
— **1101 – Frohmuhl**
— **1188 – Paris Gare du Nord 2**
— **1398 – Le Fréty St-Gorgon**
— **1399 – La Ferée**
— **1400 – Mainbressy**
— **1513 – Ire-le-Sec**
— **1534 – Marville**
— **1765 – Mauléon Brossardière**
— **1881 – Mondoubleau**
— **2080 – Kerbiquet**
— **2081 – Port-de-Carhaix**
— **2082 – Motreff**
— **2096 – Le Juch**
— **2112 – Henvic**
— **2113 – Plouenan – Kerlaudy**
— **2116 – Kernevel**
— **2117 – Scaër**
— **2125 – Guiscriff**
— **2129 – Tal-Ar-Groas**
— **2144 – St-Gérand**
— **2292 – Chiche**
— **2298 – Taillebourg**
— **2300 – Clion-sur-Seugne**
— **2302 – Fontaines-d’Ozillac**
— **2543 – Vouille**
— **3251 – Jatxou**
— **3255 – Louhossoa**
— **3266 – Dolleren**
— **3267 – Monswiller**
— **3268 – Wegscheid**
— **3269 – Zornhoff**
— **3278 – St-Gonnery**
— **3938 – Gérardmer les Bas-Rupts**
— **3941 – Gérardmer la Mauselaine**
— **3972 – Gerbeviller Foch**
— **4375 – Manduel – Redessan**
— **4549 – Cocheren Village**
— **4621 – Le Châtelard**
— **4703 – Lichtenberg**
— **4768 – Chaumont Quartier Foch**
— **4821 – Minversheim**
— **4943 – Pontivy Douric**
— **4959 – Phalsbourg**
— **4990 – Pontivy Napoléon**
— **5105 – Reipertswiller**
— **5259 – Buswiller**
— **5307 – Toulouse St-Michel**
— **5308 – Toulouse Langlade**
— **5310 – Toulouse Croix de Pierre**
— **5312 – Toulouse Jeanne d’Arc**
— **5313 – Toulouse Bellevue**
— **5554 – Toulouse la Pointe**
— **5696 – Longuyon Collège**
— **5698 – Montmédy Centre**
— **5708 – Sarrebourg Zone Industrielle**
— **5880 – Hommarting Tilleuls**
— **5881 – Arzviller Fontaines**
— **5882 – St-Louis (Moselle) Plan Incliné**
— **5883 – Guntzviller**
— **8979 – Remiremont Magdelaine**
— **8997 – Carhaix République**
— **10088 – St-Hilaire-de-Chaléons Centre**
— **10370 – Fontenay-le-Comte Gare Routière**
— **10450 – Toulouse Roseraie**
— **10509 – Myennes**
— **10528 – Uzel Aire de covoiturage (Berlouze)**
— **10800 – Loudéac Aire de covoiturage**
— **16798 – St-Louis (Moselle)**
— **16799 – Henridorff**
— **17026 – Mainbresson Centre**
— **17259 – Le Fief d’Artois**
— **17407 – Lamerey**
— **23043 – Toulouse Gironis**
— **23618 – Toulouse Chaussee**
#### Stations changed
- **747 – Lauw**
    - `sncf_is_enabled` is now disabled :x:

**Comment by anaalta** [comment]
I will close this PR and split it in more manageable parts.

**Pull request closed without merging**
