### PR TITLE
Add distribusion sicilbus stations

### PR DESCRIPTION
**Pull request by kirkgo**

### CODE REVIEW

**Comment by noplay** [comment]
I think their is a problem your original stations file is out of date . Because you are removing stations

**Comment by noplay** [comment]
distribusion_id was changed from ITCTA to ITCTACA

Are you sure for this one? The lenght seem to be a stattion instead of the city

**Comment by Ly-Jia** [comment]
> distribusion_id was changed from ITCTA to ITCTACA
> 
> Are you sure for this one? The lenght seem to be a stattion instead of the city

By the code structure, I think it is Catania Airport

**Comment by ftuyama** [comment]
There's an issue with the automap command

**Comment by kirkgo** [comment]
It's very confusing this distribusion code stations change. The code was change from from ITCTACA to ITCTA on PR open by Renan a few days ago and merged. Now, after running the stations-cli again, it changes from ITCTA to ITCTACA.

**Comment by kirkgo** [comment]
Closing this PR. It is necessary to investigate these changes made by stations-cli.

**Pull request closed without merging**
